language: ruby

deploy:
  provider: pages
  skip-cleanup: true
  github-token: github_token  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

branches:
  only:
    - gh-pages
    - /.*/
