name: b
url: https://aidanquinlan.net/b/
description:

permalink: /:title/
paginate: 10

markdown: kramdown

plugins: [jekyll-paginate, jekyll-watch, jekyll-admin, github-pages]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
