name: b
url: https://aidanquinlan.net/b
baseurl: /b
description:

permalink: /:title/
paginate: 5
paginate_path: "/page/:num"

markdown: kramdown

plugins: [jekyll-paginate, github-pages]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
