name: b
url: https://aidanquinlan.net/b/
description:

permalink: /:year/:month/:day/:title/
paginate: 10

plugins: [jekyll-paginate, jekyll-watch, jekyll-admin, github-pages]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
