---
name: b
url: https://aidanquinlan.net/b
baseurl: "/b"
description: 
permalink: "/:title/"
paginate: 10
markdown: kramdown
plugins:
- jekyll-paginate
- github-pages
exclude:
- README.md
- Gemfile.lock
- Gemfile
- Rakefile
timezone: Etc/UTC
